### ISSUE TITLE
TypeError: db.open is not a function

### ISSUE THREAD

**Issue by eviltwin** [superscriptjs/superscript#266]
I followed the [quickstart instructions](http://superscriptjs.com/starter/quickstart) to set up a simple project.

At the end the docs don't actually tell you how to start the bot, so I took a guess and tried `npm start` which then produces the following error:

```
> mybot@0.0.0 start /Users/graham/Projects/CarmenAI/mybot
> node server.js

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Number of Gambits: 0
Number of Replies: 0
/Users/graham/Projects/CarmenAI/mybot/node_modules/mongoose/lib/utils.js:413
        throw err;
        ^

TypeError: db.open is not a function
    at module.exports (/Users/graham/Projects/CarmenAI/mybot/node_modules/level-sublevel/nut.js:60:8)
    at sublevel (/Users/graham/Projects/CarmenAI/mybot/node_modules/level-sublevel/index.js:14:18)
    at module.exports (/Users/graham/Projects/CarmenAI/mybot/node_modules/level-sublevel/index.js:19:10)
    at Object.createUserDB (/Users/graham/Projects/CarmenAI/mybot/node_modules/sfacts/lib/expand.js:13:40)
    at new SuperScript (/Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/index.js:56:71)
    at /Users/graham/Projects/CarmenAI/mybot/server.js:92:3
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/lib/topics/import.js:214:11
    at Object.async.eachSeries (/Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/node_modules/async/lib/async.js:138:20)
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/lib/topics/import.js:212:15
    at Object.async.eachSeries (/Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/node_modules/async/lib/async.js:138:20)
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/lib/topics/import.js:174:13
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/node_modules/async/lib/async.js:150:25
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/lib/topics/import.js:143:11
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/node_modules/async/lib/async.js:150:25
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/lib/topics/import.js:129:17
    at /Users/graham/Projects/CarmenAI/mybot/node_modules/superscript/node_modules/async/lib/async.js:150:25
```

**Comment by wehriam** [comment]
Hi @eviltwin - can you confirm you're using version `0.2.1` of [sfacts](https://www.npmjs.com/package/sfacts) by doing an `npm upgrade sfacts` ?

There's a known issue in `0.2.0` that would cause this behavior.

**Comment by annyhe** [comment]
@wehriam I am getting the same error as @eviltwin, with sfacts version 0.2.1
```
annyhe-ltm:slackbot anny.he$ npm list --depth=0
slackbot@0.0.0 /Users/anny.he/workspace/slackbot
├── debug@2.0.0
├── mongoose@3.8.24
├── sfacts@0.2.1
└── superscript@0.11.26
```

**Comment by benhjames** [comment]
This hopefully shouldn't happen in v1.0.0 (at least I haven't come across it yet!)

**Comment by song4ever** [comment]
Have you solved this problem?
