### ISSUE TITLE
Parse error Error: Module did not self-register

### ISSUE THREAD

**Issue by miller9904** [superscriptjs/superscript#300]
When I try to install superscript, npm installs fine, but when I run `parse`, it gives me the error

```
> parse
parse topics
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/superscript/node_modules/re2/re2.js:3:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

I'm using node 5.5.0 and npm 3.3.12, running on Bash on Ubuntu on Windows.

**Comment by robguilfoyle** [comment]
I had some issues with this as well running on OSX.

First thing is first. Restart your machine.

1. `rm -rf node_modules`
2. `npm uninstall -g superscript`
3. `npm cache clean`
4. `npm rebuild`
5. `npm install -g superscript`

Give that a shot and let me know how it goes.

**Comment by miller9904** [comment]
I followed all the steps, and everything seemed to install just fine.  But now there is no `parse` command when I try to compile my `.ss` file.

**Comment by robguilfoyle** [comment]
Did you install superscript with the `-g` flag?

**Comment by miller9904** [comment]
Yes

**Comment by miller9904** [comment]
I shall try to reinstall it and make sure it was installed globally.

**Comment by miller9904** [comment]
OK, now `parse` worked!  Thanks so much!  Now I just need to figure out how to create a server to run it...

**Comment by miller9904** [comment]
When I run `# node server.js` it gives me this error:
```
# node server.js
/mnt/c/Users/secco/Documents/projects/bots/test-bot/node_modules/superscript/lib/utils.js:21
exports.trim = (text = '') => regexes.space.inner.replace(regexes.whitespace.both.replace(text, ''), ' ')
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/mnt/c/Users/secco/Documents/projects/bots/test-bot/node_modules/superscript/lib/message.js:9:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/mnt/c/Users/secco/Documents/projects/bots/test-bot/node_modules/superscript/index.js:12:15)
    at Module._compile (module.js:413:34)```

**Comment by benhjames** [comment]
Alas there are a couple of files that don't run on pre-v4 Node.js since they are running ES6 syntax. I can see a couple solutions:

* Upgrade Node to v4+ (v6 will definitely have support, v4 probably does).
* Change the offending files yourself to vanilla JavaScript (and submit a PR 😉).
* We're testing a SuperScript v1.0.0 release at the moment that will address this issue, so if you don't mind being a guinea pig, you could try installing `superscript@alpha` from npm.

Sorry for the inconvenience! We should really get that sorted for backwards Node compatibility.

**Comment by miller9904** [comment]
Success!  I upgraded to node 6.9, and everything now runs as expected.  I do get a strange error when I run the server, but it doesn't seem to affect anything.

```
# node server.js
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Users/secco/Documents/projects/bots/test-bot/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Users/secco/Documents/projects/bots/test-bot/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Number of Gambits: 1
Number of Replies: 6
Number of Gambits: 3
Number of Replies: 13
TCP server running on port 2000.
```

@benhjames I am really new to this project, and I want to mess around with the stable version before I test out the alpha.  Good to know the 1.0 release is on the way!  

Thanks to everyone who helped me with this issue.  You guys are awesome!!

**Comment by benhjames** [comment]
@miller9904 No worries, glad it's worked out! You'll probably be able to sort that error out the same way as you did the other one, probably to do with upgrading Node and not running a rebuild. Anyway, happy chatbotting! 😄
