### ISSUE TITLE
createUserFact causes crash

### ISSUE THREAD

**Issue by RichardB122** [superscriptjs/superscript#312]
I tried to reproduce the pattern demonstrated in the presentation by Rob Ellis at EmpireJS, below is my code:
```
// designed to handle specific case from Loebner Prize
+ [if] <name1> [is|be] [more|less] <adjectives> (then|than) <name2>
- ^createUserFact(<cap1>,<cap2>,<cap4>)
```
However it causes a crash when referring to the database. Here is the message:
```
TypeError: this.user.memory.create is not a function
    at Object.exports.createUserFact (/home/richard/superscript_demonstration/node_modules/superscript/plugins/user.js:64:20)
    at /home/richard/superscript_demonstration/node_modules/superscript/lib/reply/customFunction.js:75:29
    at Object.async.whilst (/home/richard/superscript_demonstration/node_modules/async/lib/async.js:792:13)
    at module.exports (/home/richard/superscript_demonstration/node_modules/superscript/lib/reply/customFunction.js:19:16)
```
I am not sure if this is stemming from me capturing input incorrectly, a database not setup properly or something else. I do not know if optional words with pipes count as captured input or not and that is throwing off my numbers. I have MongoDB setup and running and the "get" and "save" functions are working fine so I am pretty sure it is not a database issue. I am running ElementaryOS if you want to know my operating system.
***
Also I have another real quick question. Everytime I run the server after parsing it seems to add new gambits rather than replacing the old ones. Why is this happening? I think it may be causing some conflicts between them and I can't see how updated ones are working. Also how do I completely reset all the gambits so it just uses the ones in data.json?

**Comment by benhjames** [comment]
Yeah, we shouldn't be calling `memory.create` since `create` is not part of the levelgraph API. It should probably be a carbon copy of the `save` plugin but with ability to set the `predicate` i.e. verb.

Regarding the second question, this is something that we've specifically addressed for v1.0.0 (`superscript@alpha` at the moment). In the meantime, you might be able to run some variant of the `cleanup` bin script to flush everything in your database.

**Comment by RichardB122** [comment]
Alright thanks, I altered the function in my environment as a test and it is at least no longer crashing. Although the behavior doesn't seem quite right. It might be because I am still confused on the order of captured input. Do [is|be] and [more|less] count as captured input or not?

Should it be?
```
// designed to handle specific case from Loebner Prize
+ [if] <name1> [is|be] [more|less] <adjectives> (then|than) <name2>
- ^createUserFact(<cap1>,<cap3>,<cap5>)
```
Or
```
// designed to handle specific case from Loebner Prize
+ [if] <name1> [is|be] [more|less] <adjectives> (then|than) <name2>
- ^createUserFact(<cap1>,<cap2>,<cap3>)
```

**Comment by silentrob** [comment]
Optionals should not capture because they can be empty. Your second example should be correct.
```
+ [if] <name1> [is|be] [more|less] <adjectives> (then|than) <name2>
- ^createUserFact(<cap1>,<cap2>,<cap3>)
```

**Comment by RichardB122** [comment]
Alright I changed the pattern, but I can't test it without flushing the previous patterns from the database. I tried copying the cleanup.js file from bin and moving it to my project folder. I got it to work, but when I ran it with the --flush-topics command it gave me another error.
```
/home/richard/superscript_demonstration/node_modules/superscript/lib/topics/topic.js:231
        gambit.clearReplies(function() {
              ^

TypeError: Cannot read property 'clearReplies' of null
    at Promise.<anonymous> (/home/richard/superscript_demonstration/node_modules/superscript/lib/topics/topic.js:231:15)
    at Promise.<anonymous> (/home/richard/superscript_demonstration/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:96:13)
    at Promise.emit (events.js:188:7)
    at Promise.emit (/home/richard/superscript_demonstration/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/home/richard/superscript_demonstration/node_modules/mpromise/lib/promise.js:97:20)
    at Immediate.cb (/home/richard/superscript_demonstration/node_modules/mongoose/lib/query.js:1150:30)
    at Immediate.<anonymous> (/home/richard/superscript_demonstration/node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by benhjames** [comment]
`^createUserFact(...)` should now do the expected behaviour on v1.0.0. Cleanup should also work as intended!
