### ISSUE TITLE
issue while deploying in cloud foundry

### ISSUE THREAD

**Issue by shantry** [superscriptjs/superscript#355]
hi,

i gave bit int and created an application with express client, its working fine in local, but when i try to deploy it in cloud foundry, i am getting the following exception.

2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] **/home/vcap/app/node_modules/superscript/lib/bot/index.js:56**
**2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] constructor(coreChatSystem, coreFactSystem, plugins, scope, editMode, conversationTimeout, tenantId = 'master') {**
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] ^
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] SyntaxError: Unexpected token =
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at exports.runInThisContext (vm.js:53:16)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at Module._compile (module.js:373:25)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at Object.Module._extensions..js (module.js:416:10)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at Module.load (module.js:343:32)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at Function.Module._load (module.js:300:12)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at Module.require (module.js:353:17)
2017-07-06T12:07:18.232+00:00 [APP/PROC/WEB/0] [ERR] at require (internal/module.js:12:17)

can you please help me on this

**Comment by benhjames** [comment]
You'll need to run in a Node 6+ environment that supports default function parameters, as well as other nice ES6 things!

**Comment by shantry** [comment]
Thanks, i updated my node got it working..

**Comment by lgertel** [comment]
@shantry how did you fixed?
