### ISSUE TITLE
Parse fails on first install

### ISSUE THREAD

**Issue by boticello** [superscriptjs/superscript#383]
## Expected Behavior
```
cd myBotName
npm install
parse
npm run build
npm run start-[clientName]
```
Running the commands in *Getting Started*, I expected `parse` to succeed silently and enable me to continue with `npm run build`.

## Current Behavior
```
/usr/local/lib/node_modules/superscript/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/usr/local/lib/node_modules/superscript/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (/usr/local/lib/node_modules/superscript/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/superscript/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
```
## Steps to Reproduce (for bugs)
It was a clean install, first run.

## Your Environment
Mac OS X 10.12.6, Node 8.1.3, npm 5.4.2

**Comment by benhjames** [comment]
You'll need to start MongoDB first with the `mongod` command!

https://docs.mongodb.com/manual/installation/

**Comment by boticello** [comment]
```
brew install mongodb
mongod --config /usr/local/etc/mongod.conf
```
👌
